### ISSUE TITLE
Paypal integration

### ISSUE THREAD

**Issue by bekane** [ayyaninam/fred-proj1-ANDAAL#3]
Hello,
For your request, the sandbox business account information is available inside the shared document.
Please confirm that it works

**Comment by ayyaninam** [comment]
Yeah Checking it, give me some time and I will get back to you soon.

**Comment by bekane** [comment]
Ok

**Comment by ayyaninam** [comment]
is it a business account or personal account>

**Comment by ayyaninam** [comment]
?

**Comment by bekane** [comment]
business account on a sandbox env

**Comment by bekane** [comment]
do you need a personal account also?

**Comment by ayyaninam** [comment]
I'm still getting error of wrong credentials, give me 5 minutes I will get back to you.

**Comment by ayyaninam** [comment]
do paypal provide you the signature key when create the sandbox account>

**Comment by bekane** [comment]
I did not notice that. Let me check

**Comment by ayyaninam** [comment]
provide me the signature key, it is necessary.

**Comment by bekane** [comment]
can you join us here : https://meet.google.com/bqt-bhzg-mqf
