### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by bekane** [ayyaninam/fred-proj1-ANDAAL#5]
Hello,
It seems like there are some missing dependencies to run the web app.
`
(fred-proj1-ANDAAL-master) ➜  fred-proj1-ANDAAL-master python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-master-0qAgi29l/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-master-0qAgi29l/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-master-0qAgi29l/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-master-0qAgi29l/lib/python3.11/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-master-0qAgi29l/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-master-0qAgi29l/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-master-0qAgi29l/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-master-0qAgi29l/lib/python3.11/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'paypal'
`

**Comment by ayyaninam** [comment]
do you run requirements.txt file.

**Comment by ayyaninam** [comment]
I suggest you to delete the old virtualenvironement and then create a new and then hit the install -r requirements.txt command, this will fix your problem

**Comment by ayyaninam** [comment]
So for delayed reply, I see there is some issue in the email, every GitHub email is going to spam.

**Comment by bekane** [comment]
Ok no problem for the time I ran the project, the were no PayPal dependencies in the requirements.txt. il will a new copy of the repo. 
Thx

**Comment by ayyaninam** [comment]
I just deleted the paypal and do modifications in backend, now all the dependencies are in the folder already called django-oscar-paypal.

**Comment by bekane** [comment]
Ok il check it again

Le jeu. 25 janv. 2024, 17:32, Ayyan Inam ***@***.***> a
écrit :

**Comment by bekane** [comment]
Still not working when installing dependencies:
`
(fred-proj1-ANDAAL) ➜  fred-proj1-ANDAAL git:(master) ✗ pip install -r requirements.txt
Obtaining django_oscar_paypal from git+https://github.com/ayyaninam/fred-proj1-ANDAAL.git@cec4050a2207e5f0313358786ecd01f1dea905b8#egg=django_oscar_paypal&subdirectory=django-oscar-paypal (from -r requirements.txt (line 12))
  Cloning https://github.com/ayyaninam/fred-proj1-ANDAAL.git (to revision cec4050a2207e5f0313358786ecd01f1dea905b8) to /home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-CxQf_j_b/src/django-oscar-paypal
  Running command git clone --filter=blob:none --quiet https://github.com/ayyaninam/fred-proj1-ANDAAL.git /home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-CxQf_j_b/src/django-oscar-paypal
Username for 'https://github.com': ******   
Password for 'https://*****@github.com': 
  remote: Support for password authentication was removed on August 13, 2021.
  remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
  fatal : Échec d'authentification pour 'https://github.com/ayyaninam/fred-proj1-ANDAAL.git/'
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/ayyaninam/fred-proj1-ANDAAL.git /home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-CxQf_j_b/src/django-oscar-paypal did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/ayyaninam/fred-proj1-ANDAAL.git /home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-CxQf_j_b/src/django-oscar-paypal did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by bekane** [comment]
I found this:
django-oscar==3.2.2
-e git+https://github.com/ayyaninam/fred-proj1-ANDAAL.git@cec4050a2207e5f0313358786ecd01f1dea905b8#egg=django_oscar_paypal&subdirectory=django-oscar-paypal

inside the requirements.txt

**Comment by bekane** [comment]
> I just deleted the paypal and do modifications in backend, now all the dependencies are in the folder already called django-oscar-paypal.

how to use the local django-oscar-paypal I still get errors : ModuleNotFoundError: No module named 'paypal' 

And there is : 

-e git+https://github.com/ayyaninam/fred-proj1-ANDAAL.git@cec4050a2207e5f0313358786ecd01f1dea905b8#egg=django_oscar_paypal&subdirectory=django-oscar-paypal

Which doesn't work on my side

`
(fred-proj1-ANDAAL) ➜  fred-proj1-ANDAAL git:(master) ✗ pip install -r requirements.txt
Obtaining django_oscar_paypal from git+https://github.com/ayyaninam/fred-proj1-ANDAAL.git@cec4050a2207e5f0313358786ecd01f1dea905b8#egg=django_oscar_paypal&subdirectory=django-oscar-paypal (from -r requirements.txt (line 12))
  Cloning https://github.com/ayyaninam/fred-proj1-ANDAAL.git (to revision cec4050a2207e5f0313358786ecd01f1dea905b8) to /home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-2MpByTWa/src/django-oscar-paypal
  Running command git clone --filter=blob:none --quiet https://github.com/ayyaninam/fred-proj1-ANDAAL.git /home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-2MpByTWa/src/django-oscar-paypal
Username for 'https://github.com': bekane
Password for 'https://bekane@github.com': 
  remote: Support for password authentication was removed on August 13, 2021.
  remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
  fatal : Échec d'authentification pour 'https://github.com/ayyaninam/fred-proj1-ANDAAL.git/'
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/ayyaninam/fred-proj1-ANDAAL.git /home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-2MpByTWa/src/django-oscar-paypal did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/ayyaninam/fred-proj1-ANDAAL.git /home/labs/.local/share/virtualenvs/fred-proj1-ANDAAL-2MpByTWa/src/django-oscar-paypal did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by ayyaninam** [comment]
Hey, Pushed new code

**Comment by ayyaninam** [comment]
Can you check it now>

**Comment by bekane** [comment]
ok

**Comment by bekane** [comment]
can you change the requirements.txt so that I do not need to authenticate with https ? it always asks me to fill in my username and password and this doesn't work.
