### ISSUE TITLE
Flutter Wave

### ISSUE THREAD

**Issue by ayyaninam** [ayyaninam/fred-proj1-ANDAAL#6]
Hey, Do you provide me with testing keys or live keys? 

API returns me:  Merchant is not enabled for UK EU ach collections

Can you elaborate on which currency this bank account will accept on your behalf?

Ayyan

**Comment by bekane** [comment]
- The provided key is for Testing.
- Currency is XAF

**Comment by ayyaninam** [comment]
https://flutterwave.com/tz/support/general/what-are-the-currencies-accepted-on-flutterwave

Flutterwave accepts these currencies only.

**Comment by bekane** [comment]
Central African CFA Franc XAF

**Comment by ayyaninam** [comment]
XAF returns this error.

Currency not support for Token.io UK EU payment

**Comment by ayyaninam** [comment]
I see there are some mobile integrations also like GhMobile.

Can you list down all that you want?

**Comment by bekane** [comment]
- paypal
- stripe
- and flutterwave
That all for paiement gateway/method

**Comment by ayyaninam** [comment]
ok, please check my last message also, this is returning error in response.

**Comment by bekane** [comment]
make sure that the amount is an integer.

https://developer.flutterwave.com/docs/making-payments/transfers/mobile-money/

**Comment by ayyaninam** [comment]
It is in integer already

**Comment by ayyaninam** [comment]
Got it.

**Comment by ayyaninam** [comment]
Figured it out.

**Comment by ayyaninam** [comment]
I see in the documentation there are a lot of API's.

Do you want to capture the card and then charge or it is directly integrated with Play Store?

As there are both, options.

Can you give me an example how ANDAAL mobile app works on making payment with Flutter wave

**Comment by bekane** [comment]
test with the following link:
https://developer.flutterwave.com/reference/endpoints/charge#francophone-mobile-money
https://developer.flutterwave.com/docs/direct-charge/francophone-mobile-money

Look at section: Francophone Mobile Money

Sample request:
{
   "tx_ref":"MC-158523s09v5050e8",
   "amount":"10",
   "currency":"XAF",
   "country": "CM",
   "email":"user@example.com",
   "phone_number":"23700000020",
   "fullname":"Yolande Aglaé Colbert"
}

Sorry i'm busy now

**Comment by bekane** [comment]
URL: https://api.flutterwave.com/v3/charges?type=mobile_money_franco
METHOD: POST

Headers
Authorization: string

Pass your secret key as a bearer token in the request header to authorize this call. Unauthorized calls would return a 401 http code or raise unauthorized error in the different SDKs

Sample Payload:

{
"tx_ref":"MC-158523s09v5050e8",
"amount":"10",
"currency":"XAF",
"country": "CM",
"email":"user@example.com",
"phone_number":"23700000020",
"fullname":"Yolande Aglaé Colbert"
}
You can test with curl as you need

**Comment by bekane** [comment]
> I see in the documentation there are a lot of API's.
> 
> Do you want to capture the card and then charge or it is directly integrated with Play Store?
> 
> As there are both, options.
> 
> Can you give me an example how ANDAAL mobile app works on making payment with Flutter wave

only mobile money no card is need

**Comment by ayyaninam** [comment]
Just need some final tweaks and tomorrow, I will push the code with Flutterwave integration.

Can you please fill out the google doc for the next instructions?

Ayyan
